# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
      - id: uv-export # sync requirements.txt file with current dependencies
        name: uv export requirements.txt
        entry: bash -c 'mkdir -p deploy/databricks && uv export --format requirements-txt --no-hashes --no-dev --output-file deploy/databricks/requirements.txt'
        language: system
        pass_filenames: false
        files: ^(pyproject\.toml|uv\.lock)$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast # check whether file parses as valid Python code
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.0.1
#    hooks:
#    -   id: mypy # static type checker
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade # upgrade syntax for newer versions
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black # format code
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort # sort import statements