# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check # make sure the poetry configuration is not in a broken state
      - id: poetry-export # sync requirements.txt file with current dependencies
        args: ["--without-hashes", "--format", "requirements.txt", "--output", "./deploy/databricks/requirements.txt", "--only", "main"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast # check whether file parses as valid Python code
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.0.1
#    hooks:
#    -   id: mypy # static type checker
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade # upgrade syntax for newer versions
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black # format code
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort # sort import statements